### PR TITLE
Set Alert Cols to Auto

### LINKED ISSUE #206: Japanese text breaks the layout [bug report]
Apologies if it's been reported before but it seems that the Japanese text in the blue notices breaks the layout slightly (see screenshots) on iPhone 12 Pro.

image
image

### PR DESCRIPTION
**Pull request by theyokohamalife**
### How to test
Emulate on iPhone 12 Pro or 6/7/8 Plus.

### Screenshots
Screen Shot 2021-06-30 at 12 37 34 AM

### CODE REVIEW

File: components/Alert.vue [hunk 1]
```diff
@@ -2,10 +2,10 @@
   <v-container>
     <v-alert dismissible color="alertCard">
       <v-row align="center">
-        <v-col class="grow">
+        <v-col cols="auto">
```
Comment (renderf0x) [inline components/Alert.vue:5]: Slick. I'll check the Netlify preview.

**Review by renderf0x — COMMENTED** [review]
LGTM! Confirmed on the full device list in the dev console.

**Review by renderf0x — APPROVED** [review]

**Review by renderf0x — APPROVED** [review]
Great catch. I tested on a variety of browser emu presets, Xcode emu, and *this time desktop*. All looks good. We could probably use a tiny bit of padding or margin on the button when it wraps on smaller devices, but this is not urgent.
